name: FarmFix
version: '1.0-SNAPSHOT'
main: dev.cheezboi9.farmfix.FarmFix
api-version: '1.21'
commands:
  ff:
    description: Help Command for FarmFix
    usage: /<command>
    aliases: [ farmfix ]
  trample:
    description: Toggles Trample
    usage: /<command> <player> <trampleState>
  forced:
    description: Forces Trample State
    usage: /<command> <player> <forcedState>
  mobtrample:
    description: Sets ability for mobs to trample
    usage: /<command> <canTrample>
permissions:
  farmfix.trample:
    description: Allows the ability to toggle trample mode if forced trample isn't toggled
    default: true
  farmfix.harvest:
    description: Allows the ability to harvest crops using left or right click
    default: true
  farmfix.mod:
    description: Mod role for FarmFix
    default: false
